---
- hosts: 
  user: ec2-user
  become: yes
  connection: ssh
    
  vars: 
      ansible_ssh_private_key_file: "/etc/ansible/mykeypaire.pem"
      ansible_ssh_user: "ec2-user"

      tasks:
        - name: install git 
          action: yum name=git state=present

        - name: install webserver
          action: yum name=httpd state=present

        - name: restart web server
          service: name=httpd state=restarted

        - name: getting code to server
          git:
            repo: "https://github.com/pandurang6662/Monolithic_Project_29032023.git"
            dest: /var/www/html/
            version: "frontend"
